package enum

const (
	CREATED_TIME = "created_time"
	UPDATED_TIME = "updated_time"

	MAP_OBJECT_FAILED = "MAP_OBJECT_FAILED"
	NO_DOCUMENT_FOUND = "NO_DOCUMENT_FOUND"
	INVALID_SLICE     = "INVALID_SLICE"
	COUNT_FAILED      = "COUNT_FAILED"
	QUERY_FAILED      = "QUERY_FAILED"
	UPDATE_FAILED     = "UPDATE_FAILED"
	DELETE_FAILED     = "DELETE_FAILED"
	CREATE_FAILED     = "CREATE_FAILED"
	AGGREGATE_FAILED  = "AGGREGATE_FAILED"
	DISTINCT_FAILED   = "DISTINCT_FAILED"

	START_SESSION_FAILED = "START_SESSION_FAILED"
	TRANSACTION_ABORTED  = "TRANSACTION_ABORTED"
)
